name: Build Buildroot

on:
  repository_dispatch:
  workflow_dispatch:
  #schedule:
    #- cron: '0 17 * * 0'

env:
  REPO_URL: https://github.com/nationpwned/libretech-cc-buildroot
  REPO_BRANCH: master
  TZ: Asia/Jakarta

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL git.io/ubuntu-2004-openwrt)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        echo "COMPILE_STARTINGTIME=$(date +"%Y.%m.%d.%H%M")" >> $GITHUB_ENV

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt install sed make binutils gcc g++ bash patch gzip bzip2 perl tar cpio unzip rsync file bc wget python git

    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH libretech-cc-buildroot
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/libretech-cc-buildroot

    - name: Download package
      id: package
      run: |
        cd libretech-cc-buildroot
        cp configs/meson-g12a-x96-max_defconfig .config
        make download -j8
